# -*- coding: utf-8 -*-
"""database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PmAWTJFeYc7W2kk7KieOUBwDoBnX6J4o
"""

import sqlite3

def create_database():
    conn = sqlite3.connect('emails.db')
    c = conn.cursor()
    c.execute('''
        CREATE TABLE IF NOT EXISTS emails (
            id TEXT PRIMARY KEY,
            thread_id TEXT,
            subject TEXT,
            sender TEXT,
            recipient TEXT,
            date TEXT,
            body TEXT
        )
    ''')
    conn.commit()
    conn.close()

def store_email_to_db(email_id, thread_id, subject, sender, recipient, date, body):
    conn = sqlite3.connect('emails.db')
    c = conn.cursor()
    c.execute('''
        INSERT OR IGNORE INTO emails (id, thread_id, subject, sender, recipient, date, body)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', (email_id, thread_id, subject, sender, recipient, date, body))
    conn.commit()
    conn.close()